services:

  db:
    image: postgres:18.2
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: foobar


